defaults: &defaults
  host: 127.45.56.1
  port: 27010

development:
  <<: *defaults
  database: gigspotting_development

test:
  <<: *defaults
  database: gigspotting_test

# set these environment variables on your prod server
production:
  <<: *defaults
# Should be set in Heroku config