defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: gigspotting_development

test:
  <<: *defaults
  database: gigspotting_test

# set these environment variables on your prod server
production:
  host: <%= MONGO_LAB['host'] %>
  port: <%= MONGO_LAB['port'] %>
  database: <%= MONGO_LAB['database'] %>
  username: <%= MONGO_LAB['username'] %>
  password: <%= MONGO_LAB['password'] %>
